version: "3.9"
services:
  student-srv:
    build: 
      context: .
    networks:
      - students-net
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    environment:
      - MYSQL_SERVER=students-db
    depends_on:
      - students-db
  students-db:
    image: mysql:5.6
    networks:
      - students-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
    volumes:
      - type: volume
        source: students-db
        target: /var/lib/mysql
  ang-srv:
    image: saisatyateja/studentcourseangular:1.4
    environment:
      ENDPOINT_URL: http://student-srv:8080/course # This URL should work within the Docker network
    networks:
      - students-net # Connect to the same network
    ports:
      - "4200:4200" # Map container port 4200 to host port 4200
    depends_on:
      - student-srv

volumes:
  students-db:

networks:
  students-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24
